
server:
  port: 8888
spring:
  application:
    name: bootcamp-shopvintage-configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/soabel/bootcamp-shopvintage-repoconfig.git
          default-label: main
          timeout: 10
